-- AlterTable
ALTER TABLE `Campaign` ADD COLUMN `location` ENUM('ETHIOPIA', 'INTERNATIONAL', 'ADDIS_ABABA', 'AFAR', 'AMHARA', 'BENISHANGUL_GUMUZ', 'CENTRAL_ETHIOPIA', 'DIRE_DAWA', 'GAMBEELA', 'HARARI', 'OROMIA', 'SIDAMA', 'SOMALI', 'SOUTH_ETHIOPIA', 'SOUTH_WEST_ETHIOPIA_PEOPLES', 'TIGRAY') NOT NULL DEFAULT 'ETHIOPIA';
